FeatureFlagApp/Models/ErrorViewModel.cs
using System;

namespace FeatureFlagApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FeatureFlagApp/Controllers/Feature1Controller.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement;
using Microsoft.FeatureManagement.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace FeatureFlagApp.Controllers
{
    public class Feature1Controller : Controller
    {
        IFeatureManager _featureManager;
        private readonly IHttpContextAccessor httpContextAccessor;

        public Feature1Controller(IFeatureManager featureManager, IHttpContextAccessor httpContextAccessor)
        {
            _featureManager = featureManager;
            this.httpContextAccessor = httpContextAccessor;
            if (!httpContextAccessor.HttpContext.Session.Keys.Contains("StartDateTime"))
                httpContextAccessor.HttpContext.Session.SetString("StartDateTime", DateTime.Now.ToString("ddMMyyyyhhmm"));
        }

        [FeatureGate("TimeLimit")]
        public async Task<IActionResult> Index()
        {
            var startTime = DateTime.ParseExact(httpContextAccessor.HttpContext.Session.GetString("StartDateTime"), "ddMMyyyyhhmm", null);
            var elapsedTime = DateTime.Now.Subtract(startTime).Seconds;

            ViewBag.Date = elapsedTime;
            if (await _featureManager.IsEnabledAsync("TimeLimit"))
            {
                return View();
            }
            return NotFound();
        }
    }
}

FeatureFlagApp/Controllers/HomeController.cs
using FeatureFlagApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FeatureFlagApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHttpContextAccessor httpContextAccessor;

        public HomeController(ILogger<HomeController> logger, IHttpContextAccessor httpContextAccessor)
        {
            _logger = logger;
            this.httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            if (!httpContextAccessor.HttpContext.Session.Keys.Contains("StartDateTime"))
                httpContextAccessor.HttpContext.Session.SetString("StartDateTime", DateTime.Now.ToString("ddMMyyyyhhmm"));
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FeatureFlagApp/Views/Feature1/Index.cshtml
<h1>Feature 1</h1>
<p>This is the landing page of the feature 1</p>
<p>@ViewBag.Date</p>

FeatureFlagApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FeatureFlagApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FeatureFlagApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FeatureFlagApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <feature name="TimeLimit">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Feature1" asp-action="Index">Feature1</a>
                            </li>
                        </feature>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FeatureFlagApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>